-- src/main/resources/data.sql

-- Roller
INSERT INTO ROLES (NAME) VALUES ('PRODUCT_READ');
INSERT INTO ROLES (NAME) VALUES ('PRODUCT_WRITE');

-- Kullanıcılar
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES
    (1, 'temizhangozde@gmail.com', '$2b$12$dK6Xz13AHqoYNqTNuA3DOejNAG7Ry4L03NmxrlAVzWMPLCVWL28DS');
INSERT INTO APP_USER (ID, USERNAME, PASSWORD) VALUES
    (2, 'kemaltim@gmail.com', '$2b$12$dIymHl1VeUTh396IrruAKeeUTmwGk.ri40nX68rX/.w9KbwhcqLda');

-- Kullanıcı–Rol eşleştirmeleri
INSERT INTO APP_USER_ROLES (APP_USER_ID, ROLES_NAME) VALUES (1, 'PRODUCT_READ');
INSERT INTO APP_USER_ROLES (APP_USER_ID, ROLES_NAME) VALUES (2, 'PRODUCT_READ');
INSERT INTO APP_USER_ROLES (APP_USER_ID, ROLES_NAME) VALUES (2, 'PRODUCT_WRITE');

INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES (1, 'CreditCard', 'Kredi Kartı');
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION) VALUES (2, 'DebitCard', 'DebitCard');
